const PDFDocument = require('pdfkit');

// Brand colours
const COLORS = {
  background: '#0a0a0f',
  accent: '#3574f0',
  accentLight: '#5c8ff5',
  textPrimary: '#ffffff',
  textMuted: '#a1a1aa',
  sectionLine: '#2b2d30',
  definitionBg: '#1a1a26',
  definitionBorder: '#3574f0',
};

/**
 * Generates a styled PDF from the structured notes array and pipes it
 * directly into the provided writable stream (e.g., an Express response).
 *
 * @param {Array} notes - Structured notes array from noteGenerator
 * @param {import('stream').Writable} outputStream - Destination stream
 * @returns {Promise<void>}
 */
function generatePdf(notes, outputStream) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
      info: {
        Title: 'iRIS Study Notes',
        Author: 'iRIS NoteGen',
        Subject: 'AI-Generated Study Notes',
      },
    });

    doc.pipe(outputStream);
    doc.on('end', resolve);
    doc.on('error', reject);

    // ── Cover / Header ──────────────────────────────────────────────────────
    doc
      .rect(0, 0, doc.page.width, 120)
      .fill(COLORS.accent);

    doc
      .fillColor(COLORS.textPrimary)
      .fontSize(28)
      .font('Helvetica-Bold')
      .text('iRIS NoteGen', 60, 35, { align: 'left' });

    doc
      .fontSize(13)
      .font('Helvetica')
      .fillColor('rgba(255,255,255,0.75)')
      .text('AI-Generated Study Notes', 60, 72);

    const date = new Date().toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    });
    doc
      .fontSize(10)
      .text(date, 60, 95, { align: 'right' });

    doc.moveDown(4);

    // ── Note Sections ────────────────────────────────────────────────────────
    notes.forEach((section, idx) => {
      // Section heading
      doc
        .moveDown(1)
        .fillColor(COLORS.accent)
        .fontSize(16)
        .font('Helvetica-Bold')
        .text(section.heading, { continued: false });

      // Divider line
      const lineY = doc.y + 4;
      doc
        .moveTo(60, lineY)
        .lineTo(doc.page.width - 60, lineY)
        .strokeColor(COLORS.accent)
        .lineWidth(1.5)
        .stroke();

      doc.moveDown(0.8);

      // Subtopics
      if (section.subtopics && section.subtopics.length > 0) {
        section.subtopics.forEach((sub) => {
          doc
            .fillColor(COLORS.textPrimary)
            .fontSize(12)
            .font('Helvetica-Bold')
            .text(sub.title);

          doc
            .fillColor(COLORS.textMuted)
            .fontSize(11)
            .font('Helvetica')
            .text(sub.content, { lineGap: 3 });

          doc.moveDown(0.8);
        });
      }

      // Definitions
      if (section.definitions && section.definitions.length > 0) {
        section.definitions.forEach((def) => {
          // Definition box
          const boxX = 60;
          const boxWidth = doc.page.width - 120;
          const textHeight = doc.heightOfString(def.definition, {
            width: boxWidth - 30,
            font: 'Helvetica',
            fontSize: 10,
          });
          const boxHeight = textHeight + 36;

          // Check if we need a new page
          if (doc.y + boxHeight > doc.page.height - 80) {
            doc.addPage();
          }

          const boxY = doc.y;

          doc
            .rect(boxX, boxY, boxWidth, boxHeight)
            .fillColor('#1a1a2e')
            .fill();

          doc
            .moveTo(boxX, boxY)
            .lineTo(boxX, boxY + boxHeight)
            .strokeColor(COLORS.accent)
            .lineWidth(3)
            .stroke();

          doc
            .fillColor(COLORS.accentLight)
            .fontSize(10)
            .font('Helvetica-Bold')
            .text(`Definition — ${def.term}`, boxX + 14, boxY + 10, {
              width: boxWidth - 30,
            });

          doc
            .fillColor(COLORS.textPrimary)
            .fontSize(10)
            .font('Helvetica')
            .text(def.definition, boxX + 14, boxY + 24, {
              width: boxWidth - 30,
              lineGap: 2,
            });

          doc.y = boxY + boxHeight + 10;
          doc.moveDown(0.5);
        });
      }

      // Section spacer (except the last)
      if (idx < notes.length - 1) {
        doc.moveDown(1.5);
      }
    });

    // ── Footer ───────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 45;
    doc
      .moveTo(60, footerY)
      .lineTo(doc.page.width - 60, footerY)
      .strokeColor(COLORS.sectionLine)
      .lineWidth(0.5)
      .stroke();

    doc
      .fillColor(COLORS.textMuted)
      .fontSize(9)
      .font('Helvetica')
      .text(
        'Generated by iRIS NoteGen · Powered by Gemini',
        60,
        footerY + 8,
        { align: 'center', width: doc.page.width - 120 }
      );

    doc.end();
  });
}

module.exports = generatePdf;
